name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unzip project
        run: unzip maschat.zip -d maschat_extracted

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Build APK
        run: |
          cd maschat_extracted
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: maschat_extracted/build/app/outputs/flutter-apk/app-release.apk
